# Generated by Django 3.0.7 on 2020-06-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to=''),
        ),
    ]
