# Generated by Django 3.0.7 on 2020-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
