# Generated by Django 3.0.7 on 2020-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='media/project_images/'),
        ),
    ]
