# Generated by Django 3.0.7 on 2020-06-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='title',
        ),
    ]
